/** Fixed vocabulary the assistant assigns to models; shared by prompts, validation and search. */
export const AI_CATEGORIES = [
    'figurine',
    'character',
    'animal',
    'vehicle',
    'terrain or building',
    'cosplay prop',
    'tool',
    'jig or fixture',
    'replacement part',
    'bracket or mount',
    'enclosure or case',
    'container or organizer',
    'household',
    'kitchen',
    'bathroom',
    'desk accessory',
    'toy or game',
    'puzzle',
    'jewelry or wearable',
    'decoration',
    'vase or planter',
    'lamp or lighting',
    'mechanical part',
    'gear or bearing',
    'electronics accessory',
    'cable management',
    'printer accessory or calibration',
    'sign or text',
    'art',
    'other',
] as const;

export type AiCategory = (typeof AI_CATEGORIES)[number];
